name: Creates artifact

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  creates-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat <<'EOF' >> myartifact
          echo "this is legitimate text"
          EOF
      - name: Upload environment variables artifact
        uses: actions/upload-artifact@v3
        with:
          name: uploaded-artifact
          path: myartifact

  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
